export const GET_CRYPTOS_CHANGE_REQUEST = "GET_CRYPTOS_CHANGE_REQUEST";
export const GET_CRYPTOS_CHANGE_SUCCESS = "GET_CRYPTOS_CHANGE_SUCCESS";
export const GET_CRYPTOS_CHANGE_ERROR = "GET_CRYPTOS_CHANGE_ERROR";

export const META1_CONNECT_SUCCESS = "META1_CONNECT_SUCCESS";