export const trxTypes = {
    "amount": "Amount",
    "date": "Date",
    "time": "Time",
    "name": "Username",
    "received": "Received",
    "sent": "Sent",
    "last_month": "Last month",
    "last_week": "Last week",
    "24h": "24 hours",
    "from": "From",
    "to": "To",
    "account_create": "Create account",
    "account_transfer": "Transfer Account",
    "account_update": "Update account",
    "account_upgrade": "Upgrade Account",
    "account_whitelist": "Account whitelist",
    "all": "Show all",
    "assert": "Assert operation",
    "asset_bid_collateral": "Bid collateral",
    "asset_claim_fee_pool": "Claim fee pool balance",
    "asset_claim_fees": "Claim asset fees",
    "asset_claim_pool": "Claim asset fee pool",
    "asset_create": "Create asset",
    "asset_fund_fee_pool": "Fund asset fee pool",
    "asset_global_settle": "Global asset settlement",
    "asset_issue": "Issue asset",
    "asset_publish_feed": "Publish feed",
    "asset_reserve": "Burn asset",
    "asset_settle": "Asset settlement",
    "asset_settle_cancel": "Cancel asset settlement",
    "asset_update": "Update asset",
    "asset_update_bitasset": "Update SmartCoin",
    "asset_update_feed_producers": "Update asset feed producers",
    "asset_update_issuer": "Update asset issuer",
    "balance_claim": "Claim balance",
    "bid_collateral": "Collateral bid",
    "blind_transfer": "Blinded transfer",
    "call_order_update": "Update margin",
    "committee_member_create": "Create committee member",
    "committee_member_update": "Update committee member",
    "committee_member_update_global_parameters": "Global parameters update",
    "custom": "Custom",
    "execute_bid": "Execute bid",
    "fba_distribute": "Fee backed asset distribution",
    "fill_order": "Fill order",
    "htlc_create": "HTLC create",
    "htlc_extend": "HTLC extend",
    "htlc_redeem": "HTLC redeem",
    "htlc_redeemed": "HTLC redeemed",
    "htlc_refund": "HTLC refund",
    "limit_order_cancel": "Cancel order",
    "limit_order_create": "Place order",
    "override_transfer": "Override transfer",
    "proposal_create": "Create proposal",
    "proposal_delete": "Delete proposal",
    "proposal_update": "Update proposal",
    "transfer": "Transfer",
    "transfer_from_blind": "Transfer from blinded account",
    "transfer_to_blind": "Transfer to blinded account",
    "vesting_balance_create": "Create vesting balance",
    "vesting_balance_withdraw": "Withdraw vesting balance",
    "withdraw_permission_claim": "Claim withdrawal permission",
    "withdraw_permission_create": "Create withdrawal permission",
    "withdraw_permission_delete": "Delete withdrawal permission",
    "withdraw_permission_update": "Update withdrawal permission",
    "witness_create": "Create witness",
    "witness_update": "Update witness",
    "witness_withdraw_pay": "Witness pay withdrawal",
    "worker_create": "Create worker",
    "property_create_operation": "Create property",
    "property_update_operation": "Update property",
    "property_approve_operation:": "Approve property",
    "property_delete_operation": "Delete property",
    "asset_price_publish_operation": "Publish asset price"
};